package objects

// The Alert object represents an alert generated either by a thermostat or user
// which requires user attention. It may be an error, or a reminder for a filter
// change. Alerts may not be modified directly but rather they must be
// acknowledged using the Acknowledge Function.
type Alert struct {
	// The unique alert identifier. This is required to acknowledge an alert.
	AcknowledgeRef *string `json:"acknowledgeRef,omitempty"`

	// The alert date: YYYY-MM-DD
	Date *string `json:"date,omitempty"`

	// The alert time: HH:MM:SS
	Time *string `json:"time,omitempty"`

	// The alert severity. Values: low, medium, high.
	Severity *string `json:"severity,omitempty"`

	// The alert message text. Will be truncated to 500 characters if longer.
	Text *string `json:"text,omitempty"`

	// The ecobee alert message identifier
	AlertNumber *int `json:"alertNumber,omitempty"`

	// The type of alert this is. Values: alert, demandResponse, emergency,
	// message, pricing.
	AlertType *string `json:"alertType,omitempty"`

	// Whether the alert was generated by the thermostat owner
	IsOperatorAlert *bool `json:"isOperatorAlert,omitempty"`

	// Whether a reminder will be sent.
	Reminder *string `json:"reminder,omitempty"`

	// Whether to show the alert on the thermostat.
	ShowIDT *bool `json:"showIdt,omitempty"`

	// Whether to show the alert on the ecobee web portal.
	ShowWeb *bool `json:"showWeb,omitempty"`

	// Whether to send an alert email to the thermostat user.
	SendEmail *bool `json:"sendEmail,omitempty"`

	// The user acknowledgement type. Values: accept, decline, defer, unacknowledged.
	Acknowledgement *string `json:"acknowledgement,omitempty"`

	// Whether to remind the user at a later time about the alert.
	RemindMeLater *bool `json:"remindMeLater,omitempty"`

	// The identifier of the thermostat that generated the alert
	ThermostatIdentifier *string `json:"thermostatIdentifier,omitempty"`

	// The type of Alert or reminder. Possible values are: alert, hvac,
	// furnaceFilter, humidifierFilter, dehumidifierFilter, ventilator, ac,
	// airFilter, airCleaner, uvLamp, temp, lowTemp, highTemp, lowHumidity,
	// highHumidity, auxHeat, auxOutdoor. If the configuration for the specific
	// alert type is required, see NotificationSettings
	NotificationType *string `json:"notificationType,omitempty"`
}
