package objects

// The Thermostat NotficationSettings object is a container for the
// configuration of the possible alerts and reminders which can be generated by
// the Thermostat.
//
// The NotificationsSettings supports retrieval through a Thermostat GET call,
// setting the includeNotificationSettings to true in the Selection
// (https://www.ecobee.com/home/developer/api/documentation/v1/objects/Selection.shtml)
//
// The NotificationsSettings object can also be updated using the Thermostat
// POST method. When POSTing updates to this object please take a note of the
// required fields, allowed values, and notes about the email address below.
//
// The type corresponds to the Alert.notificationType returned when alerts are
// included in the selection. See Alert
// (https://www.ecobee.com/home/developer/api/documentation/v1/objects/Alert.shtml)
// for more information. When the type is anything other than alert it's
// configuration will be listed here as part of the NotificationSettings.
type NotificationSettings struct {
	// The list of email addresses alerts and reminders will be sent to. The full
	// list of email addresses must be sent in any update request. If any are
	// missing from that list they will be deleted. If an empty list is sent, any
	// email addresses will be deleted.
	EmailAddresses []string `json:"emailAddresses,omitempty"`

	// Boolean values representing whether or not alerts and reminders will be sent
	// to the email addresses listed above when triggered.
	EmailNotificationsEnabled *bool `json:"emailNotificationsEnabled,omitempty"`

	// The list of equipment specific alert and reminder settings.
	Equipment []EquipmentSetting `json:"equipment,omitempty"`

	// The list of general alert and reminder settings.
	General []GeneralSetting `json:"general,omitempty"`

	// The list of limit specific alert and reminder settings.
	Limit []LimitSetting `json:"limit,omitempty"`
}
